set nocompatible
filetype plugin on
syntax on

" VimWiki configs
autocmd VimEnter * hi VimwikiHeader1 ctermfg=red guifg=red
autocmd VimEnter * hi VimwikiHeader2 ctermfg=yellow guifg=yellow
autocmd VimEnter * hi VimwikiHeader3 ctermfg=green guifg=green
autocmd VimEnter * hi VimwikiHeader4 ctermfg=cyan guifg=cyan
autocmd VimEnter * hi VimwikiLink ctermfg=cyan guifg=cyan gui=underline term=underline
autocmd VimEnter * hi VimwikiList ctermfg=magenta guifg=magenta 

" Turn off vim bell sound
autocmd VimEnter * set vb t_vb=




call plug#begin()
" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'vimwiki/vimwiki'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'ghifarit53/tokyonight-vim'
call plug#end()
set number
set relativenumber
" Set shift width to 4 spaces.
set shiftwidth=2

" Set map
inoremap <C-H> <C-W><Backspace> 
command! Nu set relativenumber! | set nu!

" Set tab width to 4 columns.
set tabstop=2

" Use space characters instead of tabs.
set expandtab

" Do not save backup files.
set nobackup

" Do not let cursor scroll below or above N number of lines when scrolling.
set scrolloff=10

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Show partial command you type in the last line of the screen.
set showcmd

" Show the mode you are on the last line.
set showmode

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
set hlsearch

" Set the commands to save in history default number is 20.
set history=1000


set incsearch
set novisualbell
syntax enable

set ai
set si
set wrap

colorscheme dracula
" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
