#!/bin/bash

WALLPAPER_DIR="$HOME/BedRoom/_Collections/Wallpapers"
HYPRPAPER_CONF="$HOME/.config/hypr/hyprpaper.conf"  # adjust if needed
CACHE_FILE="$HOME/.cache/self_created/hyprpaper_wall_list"
CACHE_INDEX="$HOME/.cache/self_created/hyprpaper_wall_index"

# Get list of monitors
#MONITORS=$(hyprctl monitors | grep Monitor | awk '{print $2}')

# Unload all current wallpapers
hyprctl hyprpaper unload all

# Backup current config
#cp "$HYPRPAPER_CONF" "$HYPRPAPER_CONF.bak.$(date +%s)"

# Start writing new config
echo "# Auto-generated by reload_hyprpaper.sh" > "$HYPRPAPER_CONF"
echo "0" > "$CACHE_INDEX"
> "$CACHE_FILE"

# Preload images and write to config
for img in "$WALLPAPER_DIR"/*.{png,jpg,jpeg}; do
    if [ -f "$img" ]; then
        hyprctl hyprpaper preload "$img"
        echo "preload = $img" >> "$HYPRPAPER_CONF"
        echo "$img" >> "$CACHE_FILE"
    fi
done

# Optionally set first image as wallpaper
FIRST_IMG=$(ls "$WALLPAPER_DIR"/*.{png,jpg,jpeg} 2>/dev/null | head -n 1)
if [ -f "$FIRST_IMG" ]; then
    hyprctl hyprpaper wallpaper ",$FIRST_IMG"
    wal --cols16 -i "$FIRST_IMG"   
    echo "Set $FIRST_IMG as temporary wallpaper"
    # echo "wallpaper = ",$FIRST_IMG"" >> "$HYPRPAPER_CONF"
fi
echo "✔ All wallpapers preloaded and written to hyprpaper.conf"
